#**Cuaderno de ejercicios pandas**

---

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

##1.-Carga los datos del .csv https://github.com/MainakRepositor/Datasets/blob/master/F1/drivers.csv  y muestra la cabecera del dataframe.
(Usa el parametro encoding='latin1')

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Archivos .csv/drivers.csv', encoding='latin1')
df.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,NaN,HEI,Nick,Heidfeld,10/05/1977,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6.0,ROS,Nico,Rosberg,27/06/1985,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14.0,ALO,Fernando,Alonso,29/07/1981,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,NaN,KOV,Heikki,Kovalainen,19/10/1981,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

##2.- Extrae la columna última. Procura que el método que uses valga para cualquier dataframe

In [ ]:
df.iloc[:, -1]

0          http://en.wikipedia.org/wiki/Lewis_Hamilton
1           http://en.wikipedia.org/wiki/Nick_Heidfeld
2            http://en.wikipedia.org/wiki/Nico_Rosberg
3         http://en.wikipedia.org/wiki/Fernando_Alonso
4       http://en.wikipedia.org/wiki/Heikki_Kovalainen
                            ...
837     http://en.wikipedia.org/wiki/Stoffel_Vandoorne
838          http://en.wikipedia.org/wiki/Esteban_Ocon
839          http://en.wikipedia.org/wiki/Lance_Stroll
840    http://en.wikipedia.org/wiki/Antonio_Giovinazzi
841       http://en.wikipedia.org/wiki/Brendon_Hartley
Name: url, Length: 842, dtype: object

##3.- Extrae en un nuevo dataframe las columnas driverId driverRef y nationality

In [ ]:
df2 = df[['driverId', 'driverRef', 'nationality']]
df2.head()

   driverId   driverRef nationality
0         1    hamilton     British
1         2    heidfeld      German
2         3     rosberg      German
3         4      alonso     Spanish
4         5  kovalainen     Finnish

##4.- Del dataframe original obten uno nuevo que solo tenga los pilotos Britanicos

In [ ]:
df[df['nationality'] == 'British'].head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
13,14,coulthard,NaN,COU,David,Coulthard,27/03/1971,British,http://en.wikipedia.org/wiki/David_Coulthard
17,18,button,22.0,BUT,Jenson,Button,19/01/1980,British,http://en.wikipedia.org/wiki/Jenson_Button
18,19,davidson,NaN,DAV,Anthony,Davidson,18/04/1979,British,http://en.wikipedia.org/wiki/Anthony_Davidson
50,51,wilson,NaN,NaN,Justin,Wilson,31/07/1978,British,http://en.wikipedia.org/wiki/Justin_Wilson_(ra...

##5.- Obten el dataset
https://github.com/MainakRepositor/Datasets/blob/master/F1/driverStandings.csv
##Efectúa un join entre este dataframe y el de drivers por el atributo driverId

In [ ]:
df_standings = pd.read_csv('/content/drive/MyDrive/Archivos .csv/driverStandings.csv')
dfidx1 = df.set_index('driverId', inplace = False)
dfidx2 = df_standings.set_index('driverId', inplace = False)
df_join = dfidx1.join(dfidx2, how = 'inner')
df_join

,driverRef,number,code,forename,surname,dob,nationality,url,driverStandingsId,raceId,points,position,positionText,wins
driverId,,,,,,,,,,,,,,
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,1,18,10.0,1,1,1
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,9,19,14.0,1,1,1
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,27,20,14.0,3,3,1
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,48,21,20.0,2,2,1
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,69,22,28.0,3,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,giovinazzi,36.0,GIO,Antonio,Giovinazzi,14/12/1993,Italian,http://en.wikipedia.org/wiki/Antonio_Giovinazzi,68595,988,0.0,22,22,0
843,brendon_hartley,39.0,HAR,Brendon,Hartley,10/11/1989,New Zealander,http://en.wikipedia.org/wiki/Brendon_Hartley,68533,985,0.0,23,23,0
843,brendon_hartley,39.0,HAR,Brendon,Hartley,10/11/1989,New Zealander,http://en.wikipedia.org/wiki/Brendon_Hartley,68558,986,0.0,23,23,0
843,brendon_hartley,39.0,HAR,Brendon,Hartley,10/11/1989,New Zealander,http://en.wikipedia.org/wiki/Brendon_Hartley,68583,987,0.0,23,23,0
843,brendon_hartley,39.0,HAR,Brendon,Hartley,10/11/1989,New Zealander,http://en.wikipedia.org/wiki/Brendon_Hartley,68608,988,0.0,23,23,0

##6.- Mediante groupby suma los puntos de cada corredor, de forma que aparezca el apellido del corredor

In [ ]:
df_puntos = df_join.groupby(['driverId', 'surname'])['points'].sum()
df_puntos

driverId  surname
1         Hamilton      26468.0
2         Heidfeld       2830.0
3         Rosberg       16910.0
4         Alonso        18196.0
5         Kovalainen      953.0
                         ...
839       Ocon            848.0
840       Stroll          359.0
841       Giovinazzi        0.0
842       Gasly             0.0
843       Hartley           0.0
Name: points, Length: 835, dtype: float64

##7.- Del dataframe del ejercicio 6 suprime la columna url, para obtener un nuevo dataframe

In [ ]:
df_sin_url = df_join.drop(columns = 'url')
df_sin_url.head()

,driverRef,number,code,forename,surname,dob,nationality,driverStandingsId,raceId,points,position,positionText,wins
driverId,,,,,,,,,,,,,
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,1,18,10.0,1,1,1
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,9,19,14.0,1,1,1
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,27,20,14.0,3,3,1
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,48,21,20.0,2,2,1
1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,69,22,28.0,3,3,1

##8.- Con el dataframe anterior genera uno nuevo en el que el apellido aparezca como cabecera de columna y aparezca la posición en las carreras en las que ha participado (puedes usar raceId y driverStandingsId como indices). Luego extrae las columnas correspondientes a Alonso , Hamilton y Rosberg

In [ ]:
df_surname = df_sin_url.pivot(index = ['raceId', 'driverStandingsId'], columns='surname', values = 'position')
df_surname.head()
df_surname[['Alonso', 'Hamilton', 'Rosberg']]

surname                   Alonso  Hamilton  Rosberg
raceId driverStandingsId
1      8247                  NaN       NaN      NaN
       8248                  NaN       NaN      NaN
       8249                  NaN       NaN      NaN
       8250                  NaN       NaN      NaN
       8251                  5.0       NaN      NaN
...                          ...       ...      ...
988    68604                 NaN       NaN      NaN
       68605                 NaN       NaN      NaN
       68606                 NaN       NaN      NaN
       68607                 NaN       NaN      NaN
       68608                 NaN       NaN      NaN

[31726 rows x 3 columns]

##9.-Con el dataframe del ejercicio 7, añadirle tres columnas con valores enteros aleatorios con nombres col1, col2 y col3

In [ ]:
df_sin_idx = df_sin_url.reset_index()
nuevodf = pd.DataFrame(np.random.rand(df_sin_idx.shape[0], 3), columns = ['col1', 'col2', 'col3'])

df_concat = pd.concat([df_sin_idx, nuevodf], axis = 1, )
df_concat.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,driverStandingsId,raceId,points,position,positionText,wins,col1,col2,col3
0,1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,1,18,10.0,1,1,1,0.926187,0.487853,0.997037
1,1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,9,19,14.0,1,1,1,0.952357,0.873987,0.426931
2,1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,27,20,14.0,3,3,1,0.105485,0.061039,0.594533
3,1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,48,21,20.0,2,2,1,0.048894,0.983464,0.543567
4,1,hamilton,44.0,HAM,Lewis,Hamilton,07/01/1985,British,69,22,28.0,3,3,1,0.032343,0.920164,0.088319

##10.- Mostrar cuantos corredores participaron en cada carrera

In [ ]:
df_sin_idx.groupby('raceId')['driverId'].nunique()

raceId
1      15
2      20
3      20
4      20
5      20
       ..
984    24
985    25
986    25
987    25
988    25
Name: driverId, Length: 976, dtype: int64